### ISSUE TITLE
这个歌词是根据歌曲时间来显示歌词的吗

### ISSUE THREAD

**Issue by liuhui19991** [zhengken/LyricViewDemo#1]
希望作者在例子中加入歌曲和歌词,是demo可以跑起来看到效果,方便学习,谢谢

**Comment by asr-pub** [comment]
https://github.com/zhengken/LyricViewDemo/tree/master/sample  有 apk 文件、两首歌、两个歌词文件，这些应该就是你说的吧

**Comment by liuhui19991** [comment]
首先谢谢回答,我的意思是demo跑起来直接可以播放歌曲,现在是点击播放按钮提示我打开本地文件,但是我找不到打开本地文件的按钮,另外我想知道在代码中怎么改可以让我点击播放按钮时候播放网络资源的MP3,请指点

**Comment by asr-pub** [comment]
你把 mp3 和 lrc 文件 adb push 到你的 Android 设备中，然后打开 mp3 文件，选择 LyricViewDemo 运行就可以，关于播放网络资源的 MP3，这个需要自己写代码
