### ISSUE TITLE
你好，‘’http://jcenter.bintray.com/com/github/zhengken/LyricViewDemo/v1.2/LyricViewDemo-v1.2.jar'

### ISSUE THREAD

**Issue by YouthBen** [zhengken/LyricViewDemo#10]
Error:Could not HEAD 'http://jcenter.bintray.com/com/github/zhengken/LyricViewDemo/v1.2/LyricViewDemo-v1.2.jar'. Received status code 407 from server: authenticationrequired
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

**Comment by YouthBen** [comment]
这个文件貌似在jcenter上找不到了呢

**Comment by asr-pub** [comment]
https://github.com/zhengken/LyricViewDemo/releases
你到这个链接里面下载 jar 包吧
