### ISSUE TITLE
请问，您的框架如何加载本地mp3文件，查看了很多有关File帖子，都无法解决。感谢您的指导

### ISSUE THREAD

**Issue by sun2483968** [zhengken/LyricViewDemo#11]

**Comment by asr-pub** [comment]
你是想通过播放器直接打开本地 mp3 文件吗？

**Comment by sun2483968** [comment]
是的 只想加载本地mp3文件与lrc文件 但是在file写路径的时候 怎么写都不对 不知是方法有问题还是不支持呢

**Comment by sun2483968** [comment]
我将文件放到assets lrc的文件夹 
 Uri parse = Uri.parse("file:///android_assets/lrc/张敬轩-不吐不快.mp3");
//        File file = new File(new URI(parse.toString()));
        File file = null;
        try {
            file = new File(new URI(parse.toString()));
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        mLyricView.setLyricFile(file);
在这里尝试了很多写法都不可行

**Comment by asr-pub** [comment]
你连项目的 readme 都没有看过吧？  怎么能把 mp3 的路径传到 setLyricFile 里面...

**Comment by sun2483968** [comment]
您能否让您的demo 打开直接加载项目中的不吐不快文件，我就想知道这是如何运行的？您的readme我看过了 英文不好只能翻译一下  大概也明白 可是对于怎么把mp3路径正确加载 还是不知道怎么写  iOS早就搞定了 您的框架感觉简单易用 封装的很强大  所以才会这样执着。。您回答能否多花一点点时间 告诉我怎么操作 我也会把我把我的问题 粘到这里 这样可能遇到跟我一样问题的朋友也能解决

**Comment by sun2483968** [comment]
我查了很多帖子 你们也都不回复了，你的框架是不是就不能播放本地音乐文件与lrc文件？？必须要网络的？

**Comment by sun2483968** [comment]
使用你的框架我查询了很久很多的帖子 就这样放弃了 真的太可惜 你们就不能回复一下？我相信肯定不止我一个人这样的需求

**Comment by sun2483968** [comment]
我的具体需求是将几个mp3文件打包到apk中，然后读取这几个mp3文件还要有歌词功能，请问您的框架能否帮助我实现这个功能 跪谢！看到请回复一下吧。。。

**Comment by sun2483968** [comment]
苦苦等待 也没有回复 如果有跟我一样问题的朋友 建议你用lrcView 虽然星没有这个多 但是非常好用 完全解决了我的需求 而且近期也在维护更新 这作者 如果说您的框架不能满足我的需求你就告诉一下完了 何必让人这样等？我做iOS开发 实在不会写你们安卓的file 浪费了我那么久的时间

**Comment by zhengken** [comment]
如果是一个智商正常，且有学习能力的开发者，花点时间就能解决这个小问题吧！
