### ISSUE TITLE
lrc的解析

### ISSUE THREAD

**Issue by FioneraGH** [zhengken/LyricViewDemo#2]
感谢你的轮子:) 在使用中遇到一个问题，歌词[00:00.00]的解析是写死的，我在解析网易云音乐的歌词的时候部分是[00:00.000]的，解析失败，所以自己down了文件修改的，可以改进一下:0

**Comment by asr-pub** [comment]
嗯嗯，你能pull request吗？

**Comment by asr-pub** [comment]
你提的代码没通过编译啊

**Comment by FioneraGH** [comment]
奥 我的锅 提pr的时候漏掉了一行=。=
