### ISSUE TITLE
Error:(770, 60) error: cannot find symbol variable index

### ISSUE THREAD

**Issue by ManojBehera** [zhengken/LyricViewDemo#4]
LyricViewDemo Master\lyricview\src\main\java\me\zhengken\lyricview\LyricView.java
Error:(770, 60) error: cannot find symbol variable index

`private long measureStartTimeMillis(String str) {
        long minute = Long.parseLong(str.substring(1, 3));
        long second = Long.parseLong(str.substring(4, 6));
        long millisecond = Long.parseLong(str.substring(7, index)); // this index not found
        return millisecond + second * 1000 + minute * 60 * 1000;
}`

**Comment by asr-pub** [comment]
please provider your .lrc file and more detailed log
