### ISSUE TITLE
LRC格式里 [mm:ss.xx]中的xx表示百分之一秒

### ISSUE THREAD

**Issue by blackbbc** [zhengken/LyricViewDemo#5]
所以解析时间的时候，正确的时间应该是这个：

`LyricView`里的`measureStartTimeMillis(String str)`函数：

```java
return millisecond * 10 + second * 1000 + minute * 60 * 1000;
```

**Comment by ManojBehera** [comment]
Where should we keep lyrics file..it is not showing lyrics now...Showing "No Lyrics" only

**Comment by asr-pub** [comment]
@ManojBehera you should put the .mp3 and .lrc file in the same path, and the should have the same name.

**Comment by asr-pub** [comment]
@blackbbc 是哈，在你那边调整过后，歌词的效果显示如何呢？ 如果没问题的话，你可以提个Pull Request，我来合并一下代码，谢谢提供反馈
