### ISSUE TITLE
在重新设置歌词文件时有一些小问题

### ISSUE THREAD

**Issue by Godotcoffee** [zhengken/LyricViewDemo#8]
我读了一下您的源码，在1个参数的setLyricFile方法里，在设置歌词文件时有用新的歌词文件路径与mCurrentLyricFilePath变量进行比较，如果相同则不继续进行操作，并且在之前如果判断新的文件不存在或为null后在reset后就返回了。那么当我现在已经设置了一个歌词并有效的时候，接下来我设置了一个不存在的歌词文件，则View会reset变为没有歌词的显示状态，然后我又重新设置上一次有效的歌词时，因为mCurrentLyricFilePath没有变化，会导致没法将歌词重新显示出来。2个参数的setLyricFile则没有问题，但是这个没有重新设置歌词和判断编码的功能。

**Comment by asr-pub** [comment]
谢谢反馈，今天晚上我看一下

**Comment by asr-pub** [comment]
你所反馈的问题现已修复，麻烦有时间的话，可以验证一下。 PS：如果发现其他问题的话，可以提交 Pull Request，经过 review 后，我会 merge 到 master 的，谢谢 : )

**Comment by Godotcoffee** [comment]
经过验证，重新设置的问题已解决，感谢^_^
