### ISSUE TITLE
可以增加对“[02:04.12][03:37.32][00:59.73]我在这里欢笑”的这种形式的歌词解析

### ISSUE THREAD

**Issue by emhui** [zhengken/LyricViewDemo#9]
看了作者的代码，发现对于` [02:04.12][03:37.32][00:59.73]我在这里欢笑 `这种形式的歌词解析有误，于是把作者的源码给改了一下

**Comment by asr-pub** [comment]
嗯嗯，感谢反馈，您提交一个 Pull Request 吧，我合并一下代码
